#Sun PKCS#11 provider configuration file for SoftHSMv2
name = SoftHSM2
library = /usr/lib/x86_64-linux-gnu/softhsm/libsofthsm2.so
slotListIndex = 0
; attributes(*,CKO_PRIVATE_KEY,*) ={
;     CKA_DERIVE =true
;     CKA_SIGN = true
;     CKA_EXTRACTABLE =true
; }
;
; attributes(generate,CKO_SECRET_KEY,CKK_GENERIC_SECRET) = {
; CKA_SENSITIVE = false
; CKA_EXTRACTABLE = false
; }